image: java:8-jdk

variables:
  VERSION: "0.1.0"

before_script:
  - java -version
  - export GRADLE_USER_HOME=`pwd`/.gradle

mbeddr build:
  stage: build
  script:
    - pwd
    - ./gradlew tasks
    - ./gradlew -v
    - ./gradlew
  allow_failure: true
  artifacts:
    expire_in: 1 week
