variables:
  VERSION: "0.1.0"

before_script:
  - chmod +x gradlew

mbeddr build:
  stage: build
  tags:
    - java
    - gradle
    - mps
    - mbeddr
  image: java:8
  script:
    - pwd
  #   - ant -Dmps.home="/usr/MPS 3.4" -Dmbeddr.allInOne.artifacts="/usr"
    - gradle
  allow_failure: false
  artifacts:
    expire_in: 1 week
