variables:
VERSION: "0.1.0"

before_script:
- java -version
- export GRADLE_USER_HOME=`pwd`/.gradle

cache:
paths:
- .gradle/wrapper
- .gradle/caches

mbeddr build:
stage: build
tag: gradle
image: java:8-jdk
script:
- pwd
- ./gradlew tasks
- ./gradlew -v
- ./gradlew
allow_failure: false
artifacts:
expire_in: 1 week
