image: java:8

variables:
  VERSION: "0.1.0"

mbeddr build:
  stage: build
  script:
    - java -version
    - ./gradlew tasks
    - pwd
    - gradle -v
    - gradle
  allow_failure: false
  artifacts:
    expire_in: 1 week
