image: frekele/gradle

before_script:
  - java -version
  # - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
  - .gradle/wrapper
  - .gradle/caches

mbeddr build:
  stage: build
  tags: 
  - gradle
  script:
  - pwd
  - gradle -v
  - gradle
  # - ./gradlew tasks
  # - ./gradlew -v
  # - ./gradlew
  allow_failure: false
  artifacts:
    expire_in: 1 week
