variables:
  VERSION: "0.1.0"

mbeddr build:
  stage: build
  tags:
    - java
    - gradle
    - mps
    - mbeddr
  image: java:8
  script:
    - java -version
    - ./gradlew tasks
    - pwd
    - gradle -v
    - gradle
  allow_failure: false
  artifacts:
    expire_in: 1 week
