image: java:8-jdk

variables:
  VERSION: "0.1.0"

before_script:
  - java -version
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

mbeddr build:
  stage: build
  script:
    - pwd
    - ./gradlew tasks
    - gradle -v
    - gradle
  allow_failure: true
  artifacts:
    expire_in: 1 week
